apiVersion: apps/v1
kind: Deployment
metadata:
  name: payara-domain-[# th:text="${name}"/]
  labels:
    app: domain
  ownerReferences:
    - apiVersion: poc.payara.fish/v1alpha
      kind: Domain
      name: placeholder
      uid: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-[# th:text="${name}"/]
  template:
    metadata:
      labels:
        app: domain-[# th:text="${name}"/]
    spec:
      containers:
        - name: domain
          image: [# th:text="${application_image}"/]
          ports:
            - containerPort: 4848