apiVersion: v1
kind: Service
metadata:
  name: payara-node-[# th:text="${name}"/]
  labels:
    name: payara
  ownerReferences:
    - apiVersion: poc.payara.fish/v1alpha
      kind: Domain
      name: placeholder
      uid: placeholder
spec:
  type: LoadBalancer
  ports:
    - port: 28080
  selector:
    app: node
