apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payara-node-[# th:text="${name}"/]
  ownerReferences:
    - apiVersion: poc.payara.fish/v1alpha
      kind: Domain
      name: placeholder
      uid: placeholder

spec:
  maxReplicas: [# th:text="${max_instances}"/]
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payara-node
  targetCPUUtilizationPercentage: [# th:text="${cpu_target}"/]
