apiVersion: v1
kind: Service
metadata:
  name: payara-node
  labels:
    name: payara
  generateName: example-
  ownerReferences:
    - apiVersion: apps/v1
      kind: Example
      name: placeholder
      uid: placeholder
spec:
  type: NodePort
  ports:
    - port: 28080
      nodePort: 30808
      targetPort: 28080
  selector:
    app: node
