apiVersion: apps/v1
kind: Deployment
metadata:
  name: payara-operator
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: operator
          image: payara-operator:0.5
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 1000m
              memory: 256Mi